# Generated by Django 4.1.7 on 2023-03-31 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_projet_team_user_user_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project_module'),
        ),
    ]
