# Generated by Django 4.1.7 on 2023-04-03 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_task_module'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='task',
            table='Task1',
        ),
    ]
