# Generated by Django 4.1.7 on 2023-04-04 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_task_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='task',
            table='Task',
        ),
    ]
