# Generated by Django 4.1.7 on 2023-04-12 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_remove_status_statusname_status_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='status',
            new_name='statusname',
        ),
    ]
