# Generated by Django 4.1.7 on 2023-04-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_rename_status_status_statusname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='statusname',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
