# Generated by Django 4.1.7 on 2023-04-15 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_task_assign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assign',
        ),
    ]
