# Generated by Django 4.1.7 on 2023-03-20 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_is_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_manager',
            new_name='is_manager1',
        ),
    ]
